# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailerlite" do
  name "mailerlite"
  desc "Command-line interface for the MailerLite API"
  homepage "https://github.com/mailerlite/mailerlite-cli"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailerlite"

  on_macos do
    on_intel do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "231a9614ae84547b0677bffeea412861e3c6095404dfe2242cff7736238983c1"
    end
    on_arm do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "180af8afc75e741e052bb2c965c3eb0dd32136ff90cee990ce0b5fe160e7af46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_linux_amd64.tar.gz"
      sha256 "d116d6cd08f68ebaf4b12dba514f92bcbc208d6bbbb91330f911e05c43e110f3"
    end
    on_arm do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_linux_arm64.tar.gz"
      sha256 "de10ebee6bcf2676e86845c159379becc3b3d62752a9cbee5ee7a319d3c4e1f5"
    end
  end

  # No zap stanza required
end
