# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailerlite" do
  name "mailerlite"
  desc "Command-line interface for the MailerLite API"
  homepage "https://github.com/mailerlite/mailerlite-cli"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailerlite"

  on_macos do
    on_intel do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "e7258d6056d334e8d6409819e43f27afd4309eaabd6571bc8f8c986d32c1bbe4"
    end
    on_arm do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "a122d8ac044fdd6e80afec7d5385a4bdd7ea62e30ff9ec2174f13638a4fb4a1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_linux_amd64.tar.gz"
      sha256 "7a606e9ec8011adb104d1ae7ac32d449622095c0fa532d5267ee837c66f4c624"
    end
    on_arm do
      url "https://github.com/mailerlite/mailerlite-cli/releases/download/v#{version}/mailerlite-cli_#{version}_linux_arm64.tar.gz"
      sha256 "af17a40997d37d90f187cd21f46a057a5929f1c7a8a9f3fc3b208bdf7a10acf2"
    end
  end

  # No zap stanza required
end
